spring:
  application:
    name: sandbox

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  
  flyway:
    enabled: true

  graphql:
    graphiql:
      enabled: true