CREATE TABLE author (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  bio VARCHAR(255)
);

CREATE TABLE BOOK (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(512),
  author_id INTEGER REFERENCES author(id) NOT NULL
);